name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ────────────────────────────────────────────────────────────
      # 1) Installiamo Xvfb + Tcl/Tk + distutils (per python3.12)
      # ────────────────────────────────────────────────────────────
      - name: Install Xvfb, python3-tk, python3.12-distutils
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb python3-tk python3.12-distutils

      # ────────────────────────────────────────────────────────────
      # 2) Installiamo le dipendenze del progetto (usando python3)
      # ────────────────────────────────────────────────────────────
      - name: Install project dependencies
        run: |
          python3 -m ensurepip
          python3 -m pip install --upgrade pip
          python3 -m pip install -e ".[dnd,webpreview,test]"

      # ────────────────────────────────────────────────────────────
      # 3) Eseguiamo i test con python3 sotto xvfb-run (display virtuale)
      # ────────────────────────────────────────────────────────────
      - name: Run tests under Xvfb
        run: xvfb-run -s "-screen 0 1024x768x24" python3 -m pytest -q

      - name: Legacy coverage stub
        run: python3 scripts/legacy_coverage_check.py
