name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # ─── Nuovo step: installazione e avvio di Xvfb ───
      - name: Install Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x24 &
        env:
          DISPLAY: :99

      - name: Install project
        run: |
          pip install -e ".[dnd,webpreview,test]"

      - name: Run tests
        env:
          DISPLAY: :99
        run: pytest -q

      - name: Legacy coverage stub
        run: python scripts/legacy_coverage_check.py
