name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        # Non usiamo più setup-python: useremo python3 di sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-tk
          python3 -m pip install --upgrade pip

      - name: Install project dependencies
        run: python3 -m pip install -e ".[dnd,webpreview,test]"

      - name: Run tests
        run: xvfb-run -s "-screen 0 1024x768x24" python3 -m pytest -q

      - name: Legacy coverage stub
        run: python3 scripts/legacy_coverage_check.py
