# File: .github/workflows/ci.yaml

name: CI Python-Tkinter Tests

on:
  push:
    branches:
      - fix-verde-clean
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04   # <--- utilizza Ubuntu 22.04, che include python3-tk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"   # <--- NON “3.1”, ma “3.10”

      - name: Install project dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run tests under Xvfb
        run: xvfb-run -s "-screen 0 1024x768x24" python3 -m pytest -q
