name: CI Python-Tkinter Tests

on:
  push:
    branches:
      - fix-verde-clean
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          check-latest: true

      - name: Installa Tkinter e xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.10-tk xvfb

      - name: Installa dipendenze Python
        run: pip install -r requirements.txt

      - name: Run tests Trastheadless con Xvfb
        run: xvfb-run -s "-screen 0 1024x768x24" pytest -q
