name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ────────────────────────────────────────────────────────────
      # 1) Installiamo Xvfb + Tcl/Tk per il Python 3.12 di sistema
      # ────────────────────────────────────────────────────────────
      - name: Install Xvfb, python3-tk, python3-distutils
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb python3-tk python3-distutils
        # Nota: non serve installare “python3.12-tk” perché il pacchetto si chiama semplicemente python3-tk
        #       e si lega automaticamente alla versione di Python 3 (che su Ubuntu 24.04 è 3.12).

      # ────────────────────────────────────────────────────────────
      # 2) Installiamo le dipendenze del progetto con python3
      # ────────────────────────────────────────────────────────────
      - name: Install project dependencies
        run: |
          python3 -m ensurepip
          python3 -m pip install --upgrade pip
          python3 -m pip install -e ".[dnd,webpreview,test]"

      # ────────────────────────────────────────────────────────────
      # 3) Eseguiamo i test con python3 sotto xvfb-run (display virtuale)
      # ────────────────────────────────────────────────────────────
      - name: Run tests under Xvfb
        run: xvfb-run -s "-screen 0 1024x768x24" python3 -m pytest -q

      - name: Legacy coverage stub
        run: python3 scripts/legacy_coverage_check.py
