name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # Impostiamo DISPLAY a livello di job, così tutti gli step lo ereditano
    env:
      DISPLAY: :99

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ────────────────────────────────────────────────
      #  1) Installare Xvfb + Tkinter per Python 3.10
      # ────────────────────────────────────────────────
      - name: Install Xvfb and python3-tk
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb python3-tk
          Xvfb :99 -screen 0 1024x768x24 &
        # DISPLAY è già esportato a livello di job

      - name: Install project
        run: |
          pip install -e ".[dnd,webpreview,test]"

      # ────────────────────────────────────────────────
      #  2) Eseguiamo i test (ora DISPLAY=:99 è attivo ed è presente Tk/Ttk)
      # ────────────────────────────────────────────────
      - name: Run tests
        run: pytest -q

      - name: Legacy coverage stub
        run: python scripts/legacy_coverage_check.py
