name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Tkinter and Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.10-tk xvfb

      - name: Install project
        run: |
          pip install --upgrade pip
          pip install -e ".[dnd,webpreview,test]"

      - name: Run tests under Xvfb
        run: |
          xvfb-run -s "-screen 0 1024x768x24" pytest -q

      - name: Legacy coverage stub
        run: python scripts/legacy_coverage_check.py
