name: CI Python-Tkinter Tests

on:
  push:
    branches:
      - fix-verde-clean
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04    # o ubuntu-24.04 con apt-get install python3.10-tk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installa Tkinter e xvfb (solo su ubuntu-24.04)
        if: runner.os == 'Linux' && matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.10-tk xvfb

      - name: Aggiorna pip
        run: python3 -m pip install --upgrade pip

      - name: Run tests headless con Xvfb
        run: xvfb-run -s "-screen 0 1024x768x24" python3 -m pytest -q
