name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install project
        run: |
          pip install -e ".[dnd,webpreview,test]"

      - name: Run tests
        env:
          DISPLAY: ""
        run: pytest -q

      - name: Legacy coverage stub
        run: python scripts/legacy_coverage_check.py
